### ISSUE TITLE
findMidiDevices() Not Working

### ISSUE THREAD

**Issue by Euge64** [sparks/themidibus#11]
Calling findMidiDevices() doesn't seem to update the number of available devices. I used Midi.list(), then plugged in another input while constantly calling findMidiDevices() and Midi.list(), but it didn't change. The  only way to update it was to restart the application (if you could call that "update").

**Comment by sparks** [comment]
I'm closing this issue as won't fix since it's my belief that there isn't a straightforward fix. If someone figures out a way to do it, please let me know.
