### ISSUE TITLE
broken in Processing 2.2.1

### ISSUE THREAD

**Issue by rawray7** [sparks/themidibus#12]
Error message when calling MidiBus in Processing 2.2.1: "A library used by this sketch is not installed properly". Console message: "A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit  application."

**Comment by dpentecost** [comment]
I can confirm that the library is broken for me in 2.2.1

**Comment by qleonetti** [comment]
It's working for me here (using 2.2.1 too)

**Comment by sparks** [comment]
I've updated the library to work with the latest and greatest 3.0. If you're having issues with the latest version still please let me know
