### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by rob-gordon** [sparks/themidibus#14]
I'm sure I made a mistake somewhere. I git-cloned the files into my processing/libraries. Then `cd`'d in the folder and ran `ant`

    robs-mbp:themidibus robgordon$ ant
    Buildfile: /Users/robgordon/Documents/Processing/libraries/themidibus/build.xml

    compile:
        [mkdir] Created dir: /Users/robgordon/Documents/Processing/libraries/themidibus/bin
        [javac] /Users/robgordon/Documents/Processing/libraries/themidibus/build.xml:30: warning:     'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
        [javac] Compiling 9 source files to /Users/robgordon/Documents/Processing/libraries/themidibus/bin

    BUILD FAILED
    /Users/robgordon/Documents/Processing/libraries/themidibus/build.xml:30: /Applications/Processing.app/Contents/Resources/Java does not exist.

I checked and there is no Java folder in Resources, should I create it?

**Comment by sparks** [comment]
Hey,

Not sure if you still care about this issue. Sorry about the slow response.

I've updated the `build.xml` file although it's pretty hacky anyway. Basically line 8-9 of the the `build.xml` file need to point to the location where the `core.jar` and other processing core library `jar` files are located. You can see that they are now located in `Content/Java` for instance.
