### ISSUE TITLE
Send message from Processing to an other application

### ISSUE THREAD

**Issue by StanLepunK** [sparks/themidibus#18]
Hello I try to send message to DasLight 4, but it's a total fail, I open an discussion on the Processing Forum 
https://forum.processing.org/two/discussion/18146/midibus-send-midi-message

**Comment by crystalOrigin** [comment]
This is not a theMidiBus bug. Check out my reply to your question on the Processing forum.

**Comment by sparks** [comment]
Hey @StanLepunK thanks for opening an issue and sorry for the slow response. @crystalOrigin is correct this is not an issue with theMidiBus. It's a question of what device/bus you're sending your MIDI notes and CC changes to. 

In most cases if you're sending MIDI data from processing to another application you'll need to setup a virtual/internal bus on your computer. On the Mac these are known as IAC, on windows you may need to install some third party software. You can see this very good [Ableton Live article](https://help.ableton.com/hc/en-us/articles/209774225-Using-virtual-MIDI-buses-in-Live)

Once you have a virtual bus you'll basically be setting the virtual bus as the output for the processing sketch and as the input for the app you're using. So something like this

Processing + theMidiBus ---CC/note---> your virtual bus ---CC/note---> Audio app (DasLight, etc)

**Comment by StanLepunK** [comment]
No problem @sparks , thx for the answer. I try what I say @CrystalOrigin ASAP. thx for the article, I read soon.
