### ISSUE TITLE
Port Open Failed

### ISSUE THREAD

**Issue by janebeta7** [sparks/themidibus#21]
Hi, I have a problem usin midiBUs
The first time that I execute the program its all ok, but the second time, the port open failed and appears this message 

The MidiBus Warning: The chosen output device "Launch Control" was not added because it is unavailable

this is my function to setup midi

`System.out.println("----------Input (from availableInputs())----------");
    String[] available_inputs = MidiBus.availableInputs(); //Returns an array of available input devices
    for (int i = 0; i < available_inputs.length; i++) {

      //buscamos en la cadena  nanoKONTROL2 [hw:1,0,0] y Control [hw:2,0,0]
      System.out.println("["+i+"] \""+available_inputs[i]+"\"");

      if (available_inputs[i].indexOf(nano_2) !=-1 ) {

        midi_kontrol = new MidiBus(this, available_inputs[i], available_inputs[i], "midi_kontrol");
        //midi_kontrol.addInput(available_inputs[i]); //Add a new output device to busA called OutgoingC
        input_kontrol = available_inputs[i];
        isMidiAvailable = true;
        setConsola(">>>>> MIDI DETECTADO > KONTROL id:"+ i+ " "+midi_kontrol);
      }
      if (available_inputs[i].indexOf(novation) !=-1 ) {
        input_novation = available_inputs[i];
        midi_novation = new MidiBus(this, available_inputs[i], available_inputs[i], "midi_novation");
        // midi_novation.addInput(available_inputs[i]); //Add a new output device to busA called OutgoingC
 // midi_novation.close();

        isMidiAvailable = true;
        setConsola(">>>>MIDI DETECTADO > NOVATION id:"+ i+ " "+midi_novation);
      }
    }
    setConsola(">>>>MIDI input_kontrol >"+input_kontrol);
    setConsola(">>>>MIDI input_novation > "+input_novation);
    // midi_kontrol = new MidiBus(this, 2, 1, "midi_kontrol");
    //midi_novation = new MidiBus(this, 1, 1, "midi_novation");
    // setConsola(">>>>> MIDI DETECTADO > KONTROL id:"+ " "+midi_kontrol);
    // setConsola(">>>>MIDI DETECTADO > NOVATION id:"+ " "+midi_novation);
    isMidiAvailable = true;
    initLaunchControl();

    // setConsola("<< MIDI  initMIDI: >>>>>>>>>>>>>>>>>>>>>>"+midi_novation);
  }`

is it any function to close the midi port ?
thanks

**Comment by sparks** [comment]
Doing some house cleaning. Sorry I did not attend to this at the time. 

I assume this is old now so closing, if this is still an active issue you can reopen and we can discuss, I suspect this is device/driver specific and may not be easy to resolve.
