### ISSUE TITLE
MIDI Device utilized in visual arts creation

### ISSUE THREAD

**Issue by SuperMafia** [sparks/themidibus#23]
The device I'm utilizing is an MPK Mini Mk. II. And the problem I have is that I want to bind a knob's value such that I can use it to manipulate RGB values in real-time. So, for instance, Knob 1 I want to bind to alter the R (red) value, Knob 2 with G (green), and Knob 3 with B (blue). I can see that the value changes when I change the knob, but I have no idea how to code it so that the red value will take the value attributed with what's currently read by the knob.
Then I want to get it such that the class "Circles" I have can use those values, alongside being placed on a position x and y, with a growth everytime noteOn is utilized, stopping when noteOff occurs.

**Comment by sparks** [comment]
Hey @SuperMafia thanks for opening an issue here. I would suggest that you post your question on the Processing forums https://discourse.processing.org/ as it's much more a question about general programming and using processing. This issue tracker is primarily for problems and bug reports on the MidiBus. 

Sorry I can't help more
