### ISSUE TITLE
Channel 1 lag

### ISSUE THREAD

**Issue by teatralnik** [sparks/themidibus#25]
Hello.
I've connected a usb midi device and found out that messages on channel 1 are received as channel 0.
Example:
Sending: ch 1 num 1 val 1
Receiving: ch 0 num 1 val 1
Channel 2 and others are shown correctly
Also there is an error when I send ch 0.

**Comment by sparks** [comment]
Hi, thanks for submitting this. If you have a code sample that reproduces the issue we can take a look. However I don't think channel numbering issues would be occuring at the MidiBus layer, more likely in a lower level driver or midi device you are using.

If this is still a relevant issue to you please feel free to reopen and add a code sample that reproduces the issue
