### ISSUE TITLE
Sending messages outside and record in other software

### ISSUE THREAD

**Issue by pavel-b-kr12** [sparks/themidibus#26]
Is it possible to receive messages from MidiBus in other software? 

I have
```
Available MIDI Devices:
----------Input----------
[0] "2- SB X-Fi MIDI Port [CFE0]"
[1] "PCR MIDI IN"
[2] "PCR 1"
[3] "PCR 2"
[4] "Real Time Sequencer"
----------Output----------
[0] "Gervill"
[1] "Microsoft MIDI Mapper"
[2] "Microsoft GS Wavetable Synth"
[3] "2- SB X-Fi MIDI Port [CFE0]"
[4] "2- SB X-Fi Synth A [CFE0]"
[5] "2- SB X-Fi Synth B [CFE0]"
[6] "PCR MIDI OUT"
[7] "PCR"

```
I choose Output [4] and MidiBus play notes,
but nothing appears in recording and monitor software

**Comment by sparks** [comment]
Hi Pavel, yes the midibus will send message out to other software if they are able to receive it. Unfortunately I don't have a windows machine or the same software setup as you. I've recently tested this by recording midi in abeton that is played in processing. I suggest you try and simplify your setup to isolate what isn't working in your setup. 

If this is still an open issue, feel free to reopen and add a minimal code snippet that documents your issue
