### ISSUE TITLE
Not working on processing4

### ISSUE THREAD

**Issue by makakken** [sparks/themidibus#28]
Hey Guys, even if i take your basic-example, i cannot make the midibus instantiation work.

`myBus = new MidiBus(this, -1, 2);`

i get following Error: `NullPointerException`

any hints and ideas? i'm using processing4alpha6

**Comment by zerazeru** [comment]
workaround:
```java
MidiReceiver receiver = new MidiReceiver();
myBus = new MidiBus(receiver, -1, 2);
```
```java
public class MidiReceiver { 
    void noteOn(int channel, int pitch, int velocity) { /* ... */ }

    /* ... */
}
```

**Comment by makakken** [comment]
@zerazeru maybe you could document this anywhere? it works fine ;)

**Comment by sparks** [comment]
Thanks to @micycle1 for solving the issue, I have integrated his changes and released it as version 009 in the library manager

@makakken , @zerazeru this should be resolved now.

I have noticed there is sometimes also a null pointer issue when closing sketches in Processing 4 (at least on my mac). I did also look into that but I think it's a bug with the beta version of Processing 4. If you're also experiencing this issue and it continues after we exit beta please open a new issue and let me know
