### ISSUE TITLE
Processing 4 - nullPointerException

### ISSUE THREAD

**Issue by mrbbp** [sparks/themidibus#30]
Hello

i have some prob with thge lib on processing 4b2
```
import themidibus.*; //Import the library

MidiBus myBus; // The MidiBus

void setup() {
  size(400, 400);
  background(0);

  MidiBus.list(); // List all available Midi devices on STDOUT. This will show each device's index and name.
  myBus = new MidiBus(this, 0, 1);
}
```
this code **work** fine on **Processing 3.5.3** on macos 10.15.7

But does **not works** on **Processing 4b2** on macos 10.15.7

the code generate a nullPointerException error when initialise `myBus = MidiBus(this,0,1)`

<img width="279" alt="Capture d’écran 2021-12-05 à 19 13 11" src="https://user-images.githubusercontent.com/1716290/144758316-3bc58400-3870-4e5d-9b6d-f3e9efb4ba22.png">

five nullPointerException as my 5 inout!
is it a start point for debugging?

regards

éric

**Comment by sparks** [comment]
Hi @mrbbp this should be fixed as of yesterday, please update your library in the library manager to version 9. You may have to uninstall and reinstall the library if it doesn't show the update yet.

Let me know if the issue persists in version 9 for you

**Comment by mrbbp** [comment]
Great, thanks.
It works as espected.

regards
